[package]
name = "wasi-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.9", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
tokio-native-tls = "0.3.0"
toml = "0.5.9"

[dev-dependencies]
tempdir = "0.3.7"