hosts:
  html.duckduckgo.com:
    scheme: https
    request_rewrites:
      - when:
          - path:
              contains: /
        rewrite:
          match:
            header_name:
              exact: origin
            header_value:
              contains: ""
          new_header_name: $0
          new_header_value: "duckduckgo.com"
      - when:
          - path:
              contains: /
        rewrite:
          match:
            header_name:
              exact: referer
            header_value:
              contains: ""
          new_header_name: $0
          new_header_value: "https://duckduckgo.com"

  google.com:
    scheme: https
    response_rewrites:
      - when:
          - path:
              contains: /
        rewrite:
          match:
            header_name:
              exact: content-security-policy
            header_value:
              contains: ""
          new_header_name: $0
          new_header_value: "default-src 'self' google.com"
    redirect:
      to:
        url:
          url: https://duckduckgo.com
          replace_path_and_query: true

  petermalmgren.com:
    scheme: https
    request_rewrites:
      - when:
          - path:
              regex: /.*
        rewrite:
          match:
            header_name:
              exact: user-agent
            header_value:
              contains: ""
          new_header_name: $0
          new_header_value: "proxysaur"
    response_rewrites:
      - when:
          - path:
              exact: /about/
        rewrite:
          replace_with: |
            <!DOCTYPE html>
            <html>
              <body>
                <h1>Proxysaur has eaten your website.</h1>
              </body>
            </html>
      - when:
          - path:
              regex: /.*
        rewrite:
          match:
            header_name:
              exact: server
            header_value:
              contains: ""
          new_header_name: $0
          new_header_value: "proxysaur"