use * from types

http-response-get: function() -> expected<http-response, error>
http-response-set: function(resp: http-response) -> expected<_, error>
http-response-body-get: function() -> expected<body, error>
http-response-body-set: function(body: body) -> expected<_, error>