on:
  release:
    types: [created]
  pull_request:

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            rust_version: stable
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-10.15
            rust_version: stable
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - name: Compile and release ${{ matrix.os }}
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_FILES: "README.md LICENSE"