on:
  release:
    types: [created]
  pull_request:

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - build: linux
          #   os: ubuntu-latest
          #   rust_version: stable
          - build: macos
            os: macos-10.15
            rust_version: stable
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ env.rust_version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          override: true
          target: ${{ matrix.target }}
          default: true

      - name: Show version information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --locked --release --target=${{ matrix.target }}