on:
  release:
    types: [created]
  pull_request:

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - build: linux
          #   os: ubuntu-latest
          #   rust_version: stable
          - build: macos
            os: macos-latest
            rust_version: stable
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ env.rust_version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          override: true
      - name: Compile and release ${{ matrix.os }}
        run: cargo build --release